### ISSUE TITLE
Make smaller Electron apps on OS X and iOS

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#63] opened 2015-10-18 09:17 UTC
The "Electron Framework" is duplicated 3x for some reason. We can replace two of these with symlinks like this:

```
cd projectGenerator.app/Contents/Frameworks/Electron\ Framework.framework
rm Electron\ Framework
rm -rf Versions/Current/
ln -s Versions/A Current/A
ln -s Versions/Current/Electron\ Framework Electron\ Framework
```

Here is the Project Generator before:

<img width="1440" alt="screen shot 2015-10-18 at 10 58 26" src="https://cloud.githubusercontent.com/assets/157106/10563421/b2c2360a-7589-11e5-8679-26fadd605555.png">

And after:

<img width="1440" alt="screen shot 2015-10-18 at 11 14 00" src="https://cloud.githubusercontent.com/assets/157106/10563422/b6a2dd38-7589-11e5-9b2c-9e4053505778.png">

<img width="499" alt="screen shot 2015-10-18 at 10 58 48" src="https://cloud.githubusercontent.com/assets/157106/10563423/be09a930-7589-11e5-996a-b972833a0675.png">

This makes the .zip for OS X go from 224MB to 172MB.

**Comment by ofZach** [comment] 2015-10-18 11:20
this sounds reasonable.   does the same thing happen when you run 

npm run build:osx 

on osx?   I've been curious if there are differences between the platforms with regards to symlinks. 

If this is an issue with electron binary downloads (which our project is based off of) can you post an issue upstream at electron: 

https://github.com/atom/electron

for example, I saw this as part of their build process but didn't track exactly what it's doing: 

https://github.com/atom/electron/blob/master/tools/mac/create-framework-subdir-symlinks.sh

if it's not a problem with electron, it might be an issue with electron packager?

https://github.com/maxogden/electron-packager

(for example, the osx 10.8 problem was an upstream issue with unzipping empty folders, it's useful to track down which module is causing the problem, sometimes we can work our way around it.)

**Comment by ofZach** [comment] 2015-10-18 21:45
this looks like a product of being packaged on linux, here's the framework on an osx dist vs what's made via the nightlies. 

<img width="613" alt="screen shot 2015-10-18 at 5 44 59 pm" src="https://cloud.githubusercontent.com/assets/142897/10566844/06ad1394-75c0-11e5-9f20-5dd504148448.png">

**Comment by arturoc** [comment] 2015-10-21 07:50
i'm just checking this and the problem is not in the linux server which is generating the package correctly with those folders as soft links but in the zip file. zip doesn't support soft links, file permissions... that's why the linux downloads use tar.gz. When compressing the generated folder with zip it converts those links into real folders.

should we switch to tar.gz? i guess in osx it shouldn't be a problem no?

**Comment by ofZach** [comment] 2015-10-21 09:48
ah that makes sense.   Tar.gz should be fine !  Also, it looks like there might be a flag for symlinks?

http://serverfault.com/questions/265675/how-can-i-zip-compress-a-symlink

**Comment by arturoc** [comment] 2015-10-21 10:09
oh, ok i've added the symlinks flag and am regenerating the nightlies now, if that doesn't work i'll change it to tar.gz

**Comment by arturoc** [comment] 2015-10-21 10:40
i think it's fixed now:

http://ci.openframeworks.cc/versions/nightly/

it's slightly bigger than 97Mb but that could be related to the newer version of nodejs, the fodlers are now symlinks

if you want to double check just in case i'm missing something?

**Comment by ofZach** [comment] 2015-10-21 11:15
looks good!  I'm going to look at the icons now but the package seems pretty good to me

**Comment by arturoc** [comment] 2015-10-21 14:23
ok i'm going to close this then

**Closed by arturoc** 2015-10-21 14:23 UTC

**Comment by kylemcdonald** [comment] 2015-10-22 08:21
great detective work, thanks!
