### ISSUE TITLE
Error in OF_ROOT path at config.make file. (Windows / msys2 64bit  )

### ISSUE THREAD

**Issue by alexHrosas** [openframeworks/projectGenerator#314] opened 2022-11-30 06:49 UTC
I’m setting up OF in windows after a long time away from this environment. I'm new in msys2, I don’t know if I missed a step in the installation process; but at this point I'm able to compile OF and run any example successfully. 

So, I created my project with projectGenerator, then I ran ‘make’ . The following error appeared:

`make[1]: *** C:ofx/libs/openFrameworksCompiled/project/: No such file or directory. 
`
It seems to be a problem with the reverse slash. A mistaken escape char

In config.make I had
**OF_ROOT = C:\ofx**

The path seems fine but I added an escape slash to correct the path (C:\\ofx). Then I ran ‘make’ again, but it failed again. This time at the linking step (I suppose). Many errors like the following, appear: 

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe
: C:\ofx/libs/openFrameworksCompiled/lib/msys2/libopenFrameworks.a(ofImage.o):ofImage.cpp:(.text+0x1
2f8): undefined reference to `uriParseUriA'


```
So finally, I set OF_ROOT  with the unix format (because it is the same fromat  used in msys2).
**OF_ROOT = /C/ofx**

With this last change, compilation and execution runs perfectly.

**Comment by ofTheo** [comment] 2023-03-17 17:58
yeah - this is intended behavior for msys2 I believe. 
You have to use /C/ as the other way can cause issues with the backslashes being treated as escapes  - going to close this for now. 

typically we recommend using relative paths for OF_ROOT as it makes this a non issue.

**Closed by ofTheo** 2023-03-17 17:58 UTC
