### ISSUE TITLE
Project Generator Frontend - Windows - Open in IDE not working

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#377] opened 2023-06-24 22:55 UTC
In nightly releases if you generate a project and click "Open in IDE" button it doesn't open Visual Studio 2019.
This works OK in 0.11.2

**Comment by ofTheo** [comment] 2023-07-16 02:32
@dimitre can you try the latest from here? 
hoping some of the macOS fixes help with Windows too.

**Comment by dimitre** [comment] 2023-07-29 02:27
Hey @ofTheo I've finally tested more in Windows, still not opening in IDE.

**Comment by danzeeeman** [comment] 2023-08-28 04:07
Just ran into this with the nightly

**Comment by ofTheo** [comment] 2023-08-28 20:39
Could it be this line?
https://github.com/openframeworks/projectGenerator/blob/master/frontend/index.js#L1098 

The  `|| 'ios'` looks suspect. 

This line is not being reached: 
https://github.com/openframeworks/projectGenerator/blob/master/frontend/index.js#L1127

But the function in app.js which calls the index.js function is getting called, so I think the issue is somewhere in `ipcMain.on('launchProjectinIDE', (event, arg) => {` in index.js

**Comment by ofTheo** [comment] 2023-08-28 20:40
Might be result of this PR:
https://github.com/openframeworks/projectGenerator/pull/365

**Comment by ofTheo** [comment] 2023-08-28 22:42
closed by 45f7638
https://github.com/openframeworks/projectGenerator/commit/45f7638c3ab5273fc8e1f34716395111a75d7671

**Comment by ofTheo** [comment] 2023-08-28 22:42
fixed in the OF/OF nightly builds ( just rebuilt )

**Closed by ofTheo** 2023-08-28 22:42 UTC
Labels: frontend
