### ISSUE TITLE
Overwrites xcode groups when updating a project with addons

### ISSUE THREAD

**Issue by tomchambers2** [openframeworks/projectGenerator#129] opened 2016-05-30 14:36 UTC
If you have an existing project and update it with the project generator, it generates a new xcodeproj file (I think) and destroys groups. This can be quite frustrating if there are a lot of files nicely ordered.

**Comment by ofZach** [comment] 2016-05-30 15:00
I don't think there's a great way of preserving anything from the Xcode project since we don't parse that and that file gets overwritten.  We do recursively parse the src folder so if things are organized there those groups are reflected.  I don't think it's likely that the pg would every parse Xcode project files so I'm not sure there's a chance to fix this.  Maybe the of Xcode plugin can help here ?

**Comment by kritzikratzi** [comment] 2016-05-30 16:09
hey!

if you're willing to venture into the experimental world you can use
"ofxcode":
(download a binary release from https://github.com/kritzikratzi/ofxcode and
drop it in /usr/local/bin/ )

then run "ofxcode sync" in the project directory. this remove all addon
groups and re-adds them based on the addons.make file. (or type "ofxcode
update ofxSomePlugin" to update/add/remove a single plugin).

some notes:
- the first time you try this, make sure you have a copy of your
.xcodeproject
- i'm developing this for my own projects, it handles dylibs and addon-data
folders a bit differently than the PG
- "ofxcode sync" _will_ soon also remove and re-add the source folder.
there will be "ofxcode sync src" and "ofxcode sync addons", but i can't
remember how much of this i programmed already
- local addons are not yet supported


best, hansi.

**Comment by ofTheo** [comment] 2020-08-06 16:02
going to close this as its not a bug and a fix would require rethinking the whole PG system.
:)

**Closed by ofTheo** 2020-08-06 16:02 UTC
