### ISSUE TITLE
Error when using relative path for project

### ISSUE THREAD

**Issue by Sonic803** [openframeworks/projectGenerator#327] opened 2023-03-17 16:17 UTC
Running
`./apps/projectGenerator/commandLine/bin/projectGenerator -vo. ./apps/myApps/test`
gives
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot make absolute path: Invalid argument []
Aborted (core dumped)
```
while using an absolute path for the project works.

In an older version of the project generator ( the one that came with of_v20230123_linux64gcc6_release ) using a relative path for the project worked

**Comment by dimitre** [comment] 2023-03-17 18:15
@ofTheo a curious question here, because I've never used PG like this.
I've always thought the -o parameter was related to the project path, like "../../.."
in this case @Sonic803 proposes we have the -o parameter is related to current folder and we calculate the right of path inside PG, is that the intended behavior?

**Comment by ofTheo** [comment] 2023-03-17 18:50
yeah @dimitre I am not sure if the above is correct. 

I believe 
-o should be the absolute or relative path from the pg binary to the OF root. 

See: https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/main.cpp#L14

**Comment by ofTheo** [comment] 2023-03-17 18:51
but it might be that @Sonic803 is also running into the bug in #329 or related bug with the missing /

**Comment by Sonic803** [comment] 2023-03-17 21:52
The problem was not `--ofPath`, that i think is relative to the location where the command is run so running it from the root of openframeworks using `-o.` works ( it works also with the absolute path ).
It was the path to the project that for some reason doesn't work if it is relative.
The gui of the project generator still works because it passes both with absolute paths.

**Comment by ofTheo** [comment] 2023-03-17 23:00
Thanks @Sonic803 I think the error is here: 

https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/main.cpp#L511 

`projectPath = of::filesystem::absolute(projectPath).string();`

I think it should be

`projectPath = of::filesystem::absolute(projectName).string();`

As projectPath is empty and projectName is the input from the command line.

**Comment by ofTheo** [comment] 2023-03-17 23:02
> Shouldn't -o be the absolute or relative path from the project path to 
No I think that all gets resolved in the PG app. PG basically needs to know where OF is relative to it and then it can handle everything else.

**Comment by ofTheo** [comment] 2023-03-17 23:08
So [this change](https://github.com/openframeworks/projectGenerator/issues/327#issuecomment-1474492038) fixes it for me. 
Will push a fix up and let me know if works for you @Sonic803

**Closed** 2023-03-17 23:38 UTC

**Comment by Sonic803** [comment] 2023-03-18 07:09
It works now
