### ISSUE TITLE
OF_PATH set incorrectly in make files

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/projectGenerator#404] opened 2023-08-11 02:18 UTC
Hi, 
I just wanted to point out that OF_PATH is not being set correctly, which becomes very clear when you update rather than create a project.
Apparently, instead of overwriting whatever there is it appends, thus OF_PATH keeps on growing and growing.

**Comment by dimitre** [comment] 2023-08-11 03:15
which platform / template are you using? I'll be testing now for macOS to try and reproduce the issue

**Comment by roymacdonald** [comment] 2023-08-11 03:28
macos bigsur 11.6.8. no template. Just whatever is default.
on commit:
 74c435abf6ccab966b8c3cac7c4567f62a7bbf33 (HEAD -> master)
Author: Dimitre <dimitre@users.noreply.github.com>
Date:   Mon Jul 31 13:19:54 2023 -0300

    Fix15 : cleanup, OF PG Version (#397)
    

If you just create a new project, and then  check its makefile and config.make files. The first time the relative path will probably be OK. But then update again and check these files for OF_ROOT and you will notice that each time `../` gets added (actually some times it is more than just one `../`)

**Comment by dimitre** [comment] 2023-08-11 14:08
I've tried to reproduce here with no success. can you please post the entire command to make it happen?  are you using commandLine or frontend?

**Comment by roymacdonald** [comment] 2023-08-12 13:06
Hi. I am just using the front end. 
Just open PG create a new project, dont open in ide as it is not necesary, dont close PG. Check the makefile, where it sets OF_ROOT.  In PG hit update. Now check thr makefile. Notice how the OF_ROOT now is different

**Comment by dimitre** [comment] 2023-08-12 13:50
I've now created a project with all default settings, OFW/apps/myApps/myLikeableSketch
and regenerate it but it Makefile contents seems to be the same here:
```make
# Attempt to load a config.make file.
# If none is found, project defaults in config.project.make will be used.
ifneq ($(wildcard config.make),)
	include config.make
endif

# make sure the the OF_ROOT location is defined
ifndef OF_ROOT
	OF_ROOT=$(realpath ../../..)
endif

# call the project makefile!
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk

``` 
Let me know if I need to do something else to reproduce. I'm using nightly from yesterday, it outputs ```[notice ] PG v.19``` so I know it is using the latest commandLine version internally.

**Comment by ofTheo** [comment] 2023-08-12 21:06
@dimitre I think @roymacdonald is talking about the config.make file in the app directory not the actual makefile ie:
`OFW/apps/myApps/myLikeableSketch/config.make`

**Comment by dimitre** [comment] 2023-08-12 21:11
thanks for the clarification. I still cannot reproduce here:
can you double check @ofTheo to see if it is happening there?

here is the start of config.make after subsequent pg generation
```make
################################################################################
# CONFIGURE PROJECT MAKEFILE (optional)
#   This file is where we make project specific configurations.
################################################################################

################################################################################
# OF ROOT
#   The location of your root openFrameworks installation
#       (default) OF_ROOT = ../../.. 
################################################################################
OF_ROOT = ../../..

################################################################################
# PROJECT ROOT
#   The location of the project - a starting place for searching for files
#       (default) PROJECT_ROOT = . (this directory)
#    
```

**Comment by ofTheo** [comment] 2023-08-12 21:26
@roymacdonald can you try the very latest OF download from:
https://github.com/openframeworks/openFrameworks/releases

I think this is not happening in the nightly builds. ( at least I updated an app multiple times and didn't see it in config.make or makefile )

**Comment by roymacdonald** [comment] 2023-08-13 01:53
Ok. I figure out what the problem is.
It happens when you make a project at a path that is not at the "standard" project folder depth. So, if your app is at `openFrameworks/app/myApps/myAwesomeProject` it will work with no problems. But if you set it to be at any other depth it does not work and the issue I mention appears, for example making  a project at `openFrameworks/app/myApps/moreApps/myAwesomeProject`

Also, in such case, it sets  OF_ROOT to be an absolute path, even when the project is actually nested within OF_ROOT.

**Comment by dimitre** [comment] 2023-08-13 02:24
Ok I can reproduce and I've fixed in this PR. 
https://github.com/openframeworks/projectGenerator/pull/405
will be merging soon if it passes tests. PG version is now 20

**Closed** 2023-08-13 02:36 UTC

**Comment by roymacdonald** [comment] 2023-08-13 03:26
@dimitre awesome. thanks!

**Comment by dimitre** [comment] 2023-08-13 15:46
Thank you @roymacdonald !
